### ISSUE TITLE
About your Code

### ISSUE THREAD

**Issue by DippinHigh** [41john/NFL.bundle#12]
Hi

I'm trying to understand your code, because I'd like to disable autonegotiation.
The reason is that in my local Network, I have the poorest quality on live games (DLNA or Samsung TV Plex App). When i enable direct play, live Games don't play live, instead they start at the previewshow.
Firstly i like to fasten quality to 4.5MBit.
secondly, is it possible to use the 6MBit Stream? (Chromcast 'only'?)

Thank you!

**Comment by DippinHigh** [comment]
(Problems only in LAN, WAN no issues)

**Comment by 41john** [comment]
Since Plex are removing all support for channels/plugins from clients I'm not putting any more work into it. It is a shame as it had been a hobby of mine for some time.

You are correct there are some weird quirks with Plex in how it plays the streams from this plugin. These are all Plex Media Server issues with how Plex have set the profiles to handle HLS streams when it sees one. As NFL Gamepass uses encrypted HLS streams and they are sometimes of live content, PMS did some odd things and tried to transcode the stream even though all the major plex clients would play perfectly if it instead direct played them. This will explain why it works outside your LAN as PMS must choose to direct play in that scenario.

Regarding 6Mbit streams, you are welcome to fork this project and edit the https://github.com/41john/NFL.bundle/blob/master/Contents/Services/URL/NFL/ServiceCode.pys
file and change this over. There are some guys that have a similar plugin for kodi that could be worth looking at, it can be found here https://github.com/aqw/xbmc-gamepass
