### ISSUE TITLE
GamePass is moving from Neulion to a new partner

### ISSUE THREAD

**Issue by aqw** [41john/NFL.bundle#6]
Hey @41john 

I'm the maintainer of the GamePass addon for Kodi, and we've just learned that it looks like just about everything is changing with the GamePass service.[1][2] The good news is that is looks like they're still using m3u8 and HLS, so the underlying technology is the same. But all the servers are different as are the server responses.

If you're interested, it would be great to coordinate on this and share the effort of updating our addons. In my project, we've done our best to keep the Kodi bits and the GamePass bits separate, in the hope that one day we could cooperate with another project. This seems as good of a time as any to re-extend the offer. :-)

All of our non-Kodi bits are in a library called pigskin.py[3], and is meant to be completely agnostic from whatever UI (Plex, Kodi, or otherwise) is used to display the data/videos.

Let me know what you think. :-)

---Alex

[1] https://github.com/aqw/xbmc-gamepass/issues/289
[2] http://www.sportspromedia.com/news/nfl-agrees-new-partnerships-to-drive-game-pass-growth
[3] https://github.com/aqw/xbmc-gamepass/blob/master/resources/lib/pigskin.py

**Comment by 41john** [comment]
Would be interested in sharing efforts to get this working. Please keep in touch as you make a start on this, I will do the same too.

--John.

**Comment by aqw** [comment]
@41john Excellent.

We have made quite a bit of progress already, and already have it working with the new service.

There is, however, lots of cleanup to do and testing. And we expect more breakage (as Game Pass loves to do). So, there's still plenty of work to come.

---Alex

**Comment by 41john** [comment]
Wow, that was fast! I have been away for the past week so no time to look at it, but will do so before the new season gets up and running. I will keep an eye on what you have done, and make use of it where possible and if I can provide any answers to any of your to do's I will be sure to pass comment.

**Comment by aqw** [comment]
Well, @kaileu deserves most of the credit. That man was on a mission. ;-)

I also don't have time right now, but hope to in a couple weeks. Perhaps our timelines will line up.

Best of luck with re-entry into life. :-)

---Alex

**Comment by seanarnold** [comment]
@41john have you had time to start this development? If not, I used this channel all last year and as a developer myself I'm keen to help out.

**Comment by aqw** [comment]
@seanarnold @41john A quick update on where things are with my addon and also my understanding of what Game Pass is doing. From what we can tell:

* Game Pass Domestic is dead and the NFL is pushing users towards the NFL app, but that service lacks many of the features of Game Pass and/or requires links with certain cable providers. This is impossible for our addon to support as the content is balkanized across too many providers and geographic regions.
* Game Pass Europe was created using a new streaming partner. Our addon has (nearly) complete support for this (aqw/xbmc-gamepass#294).
* Game Pass International lives on and covers the rest of the world. However, NeuLion (predictably) changed a lot of their API, and our old code no longer works with their service. Unfortunately, all of our developers are in Game Pass Europe regions. We are seeking an interested developer with a Game Pass International subscription to help add support (aqw/xbmc-gamepass#313).

If you're still interested in using pigskin.py, we'd be happy to work with you, merge patches, and make changes to ensure pigskin.py is useful for more than just Kodi. The separation between default.py (kodi specific) and pigskin.py is reasonably clean, but no one outside of our addon (to our knowledge) has ever used it, so that's all just theory up until now. ;-)

---Alex

**Comment by 41john** [comment]
Yes started development on this. Hit one issue which seems to be with the Plex framework, but will discuss this with some others Plex channel developers when I have the time.

I looked at the idea at code sharing with the kodi addon but I think at this time it seems a bigger project, as due to the Plex channel framework it would not be simple to achieve this.

At this time it seems easier to potentially manually take some code if I need it. Though I have most things done now just a few bugs to iron out. Though it can be the bugs that can be most time consuming to resolve!

It should be ready for the start of the regular season.

**Comment by seanarnold** [comment]
@41john can you push your code onto a new branch so I can have a look & help out.
I think working on `pigskin.py` would be a good long term decision as it will be supported by more people long term, but that's up to you :) 

Let me know where I can help

**Comment by kaileu** [comment]
@41john that would be great if you can push your start to the repository sowe can try to help :-)

**Comment by 41john** [comment]
Will try and tidy up the code and post it later today if I get time. At the moment it is quite a mess and I don't want to post it until it is in better shape.

I have most of the menus in gamepass loading correctly, the URL Service code is also almost there too but is currently a mess and so that is what I need to work on and tidy up.

I think the only thing I really need help with, as I'm stuck on (and when sorted will mean we having a working channel) is when I do a post to this URL https://www.nflgamepass.com/api/user/api/users/v1/videoentitlement/diva/open

I post all the correct values however as previously discussed with @kaileu in a PM, it seems to be doing the post using a normal post and not a json post. I have been trying to work on achieving a successful response from my post but so far have not had any luck. Even when trying a header of "Content-Type: application/json". 

I would really appreciate if either of you can give me some code that works in plex to do the post I'm on about. I know @kaileu you will understand this well having done this for the kodi add on, @seanarnold hopefully looking here will help you understand in case you can help https://github.com/aqw/xbmc-gamepass/blob/master/resources/lib/pigskin.py#L299

This week is quite a hectic week for me, but from next Sunday onwards I'm hoping to put the time in and get this done.

**Comment by seanarnold** [comment]
Hi there 
Firstly is the NFLgamepass.com for International subscribers? In my code I ended up using gamepass.nfl.com instead. 
You can see how far I've got with international Pigskin in my repo. This might help you with initiating the stream: https://github.com/seanarnold/xbmc-gamepass/blob/international-support-2017/resources/lib/pigskin.py#L288
I'd be keen to compare our code to see if they are compatible with each other. Mine was based mostly of what the iOS app is doing. 
Cheers
		
		

		
	





On Sun, Aug 20, 2017 at 11:46 PM +1200, "41john" <notifications@github.com> wrote:












Will try and tidy up the code and post it later today if I get time. At the moment it is quite a mess and I don't want to post it until it is in better shape.


I have most of the menus in gamepass loading correctly, the URL Service code is also almost there too but is currently a mess and so that is what I need to work on and tidy up.


I think the only thing I really need help with, as I'm stuck on (and when sorted will mean we having a working channel) is when I do a post to this URL https://www.nflgamepass.com/api/user/api/users/v1/videoentitlement/diva/open


I post all the correct values however as previously discussed with @kaileu in a PM, it seems to be doing the post using a normal post and not a json post. I have been trying to work on achieving a successful response from my post but so far have not had any luck. Even when trying a header of "Content-Type: application/json".


I would really appreciate if either of you can give me some code that works in plex to do the post I'm on about. I know @kaileu you will understand this well having done this for the kodi add on, @seanarnold hopefully looking here will help you understand in case you can help https://github.com/aqw/xbmc-gamepass/blob/master/resources/lib/pigskin.py#L299


This week is quite a hectic week for me, but from next Sunday onwards I'm hoping to put the time in and get this done.

**Comment by 41john** [comment]
@seanarnold You must be outside Europe. I'm coding for the changes to NFL Gamepass in Europe, where they have a new provider called WPP/Bruin. If you are outside Europe the gamepass service is still with Neulion, and therefore the code currently posted in this repository should be close to working, though I know Neulion have made a few minor changes this year. So you just need to fix it to work with those changes.

My plan is to get the plex channel working with the WPP/Bruin platform (Gamepass Europe). This is completely different to what you are trying to do. I can't work on getting it to work with the Neulion platform anymore as Gamepass Europe subscribers can't even use the Neulion service through a VPN.

What I would like to do via the plex forums is once you or others also on the plex forums working on a Non Europe Gamepass plex channel get a working channel, that at first it is released as a seperate download for users to manually installed, and then within a few weeks it is merged into my channel.

**Comment by kaileu** [comment]
@41john if you will upload your current State to github i will looking into the post Problem.
As i never coded for Plex it would be helpful for me to Trial and Error with a nearly working Code.

**Comment by jonahtaxt** [comment]
@41john I'm currently in Mexico and have the International Gamepass version. I would be more than glad to help out but, I honestly have never developed a plex plugin. If at somepoint we could chat a little more, I would be more than glad to help out and have the channel running for Gamepass international as well

**Comment by aqw** [comment]
Just as FYI, the Kodi addon's python library for NFL Game Pass has been separated into its own project (aqw/pigskin). We still don't have Game Pass International support yet (lacking a developer with the subscription), but hope sprints eternal (aqw/pigskin#1).

Not sure if there's still interest in using the pigskin library, but from my perspective, it would be wonderful to pool our efforts.

---Alex

**Comment by 41john** [comment]
I feel like until my plex channel needs a major rewrite I don't have the time to integrate into this at the moment. My Plex channel only supports the European gamepass at the moment, and even that needs some minor work before the start of the regular season.

**Comment by aqw** [comment]
@41john No worries. Just an offer. :-)

The project will continue to live there, if you ever need it.

If you want, I can let you know if we ever get International support re-added.

Best of luck with the 2018 season. :-)

---Alex
